---
- name: Installer Apache et PHP 8 sur AlmaLinux
  hosts: 192.168.0.44
  become: true
  tasks:

    - name: Installer les dépendances
      dnf:
        name:
          - epel-release
          - dnf-utils
        state: present

    - name: Activer le module PHP 8.2 (ou 8.1, 8.0)
      command: dnf module enable php:remi-8.2 -y
      args:
        creates: /etc/dnf/modules.d/php.module

    - name: Installer Apache et PHP 8
      dnf:
        name:
          - httpd
          - php
          - php-cli
          - php-common
          - php-mysqlnd
        state: present

    - name: Activer et démarrer Apache
      systemd:
        name: httpd
        enabled: true
        state: started
