---
 - name: Installer Apache et PHP 8 sur AlmaLinux
   hosts: 192.168.0.44
   become: true
   tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: Custom Web Page

    - name: http service enable
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: open firewall
      ansible.posix.firewalld:
        port: 80/tcp
        state: enabled
        immediate: yes
        permanent: yes

    - name: Enable Remi PHP 8.4 module
      ansible.builtin.command: dnf module enable php:remi-8.4 -y
        state: present

    - name: Install PHP 8.4 and common modules
      ansible.builtin.dnf:
        name:
          - php
          - php-cli
          - php-common
          - php-fpm
          - php-mysqlnd
          - php-pdo
          - php-opcache
          - php-gd
          - php-mbstring
          - php-xml
          - php-json
          - php-devel
        state: present
        
