---
 - name: Installer Apache et PHP 8 sur AlmaLinux
   hosts: 192.168.0.44
   become: true
   tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: Custom Web Page

    - name: http service enable
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: open firewall
      ansible.posix.firewalld:
        port: 80/tcp
        state: enabled
        immediate: yes
        permanent: yes

    - name: Download Remi RPM without cert check (unsafe)
      ansible.builtin.get_url:
        url: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
        dest: /tmp/remi-release.rpm
        validate_certs: no

    - name: Install Remi RPM
      ansible.builtin.dnf:
        name: /tmp/remi-release.rpm
        state: present

    - name: Enable Remi PHP 8.1 module
      ansible.builtin.command: dnf module enable php:remi-8.1 -y
      args:
        warn: false

    - name: Install PHP 8.1 and common modules
      ansible.builtin.dnf:
        name:
          - php
          - php-cli
          - php-common
          - php-fpm
          - php-mysqlnd
          - php-pdo
          - php-opcache
          - php-gd
          - php-mbstring
          - php-xml
          - php-json
          - php-devel
        state: present

    - name: Ensure PHP-FPM is enabled and started
      ansible.builtin.service:
        name: php-fpm
        state: started
        enabled: yes
