---
 - name: Installer Apache et PHP 8 sur AlmaLinux
   hosts: 192.168.0.44
   become: true
   tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: Custom Web Page

    - name: http service enable
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: open firewall
      ansible.posix..firewalld:
        service: httpd
        state: enabled
        immediate: true
        permanent: true
