---
 - name: Installer Apache et PHP 8 sur AlmaLinux
   hosts: 192.168.0.44
   become: true
   tasks:
    - name: Installer les dépendances
      dnf:
        name:
          - epel-release
          - dnf-utils
        state: present
    - name: Install Remi repository
      dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
        state: present	
	- name: Enable Remi module (example: PHP 8.1)
      shell: dnf module enable php:remi-8.1 -y
      args:
        warn: false
    - name: Install PHP 8.1 from Remi
      dnf:
        name: php
        state: present
